### ISSUE TITLE
Compilation issues (related to ncbi-vdb-sys) on MacOS

### ISSUE THREAD

**Issue by rob-p** [ArcInstitute/xsra#39]
I tried to compile on my (M1 Max) MacOS 15.2 laptop, and everything was fine and dandy until we get to `ncbi-vdb-sys`.  There are many compiler warnings there, but a couple of errors show below.

```
  /Users/rob/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ncbi-vdb-sys-0.1.5/vendor/ncbi-vdb/libs/schema/zz_schema-ast.cpp:72:25: note: expanded from macro 'yynerrs'
     72 | #define yynerrs         AST_nerrs
        |                         ^
  1 warning generated.
  /Users/rob/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ncbi-vdb-sys-0.1.5/vendor/ncbi-vdb/libs/klib/status-rc.c:49:21: error: call to undeclared function 'strchrnul'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
     49 |     return (size_t)(strchrnul(str, ' ') - str);
        |                     ^
  /Users/rob/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ncbi-vdb-sys-0.1.5/vendor/ncbi-vdb/libs/klib/status-rc.c:49:21: note: did you mean 'strchr'?
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_string.h:76:7: note: 'strchr' declared here
     76 | char    *strchr(const char *__s, int __c);
        |          ^
  /Users/rob/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ncbi-vdb-sys-0.1.5/vendor/ncbi-vdb/libs/klib/status-rc.c:49:41: error: invalid operands to binary expression ('int' and 'const char *const')
     49 |     return (size_t)(strchrnul(str, ' ') - str);
        |                     ~~~~~~~~~~~~~~~~~~~ ^ ~~~
  2 errors generated.
  make[3]: *** [libs/klib/CMakeFiles/klib.dir/status-rc.c.o] Error 1
  make[2]: *** [libs/klib/CMakeFiles/klib.dir/all] Error 2
  make[2]: *** Waiting for unfinished jobs....
```

Presumably, these are a few C-isms that more permissive compilers are happy to accept, but which Apple clang rejects.  Have you encountered this before? Are you aware of compilation issues on MacOS? If you want to move this issue to the `ncbi-vdb-sys` repo instead, please go ahead.

**Comment by noamteyssier** [comment]
yeah definitely an issue with compiling `ncbi-vdb` - I ran into an issue compiling it after an update to my M3. I'll move this issue to that repo and I'll patch it there

**Comment by noamteyssier** [comment]
hey @rob-p, c

**Comment by rob-p** [comment]
Thanks @noamteyssier.  My laptop (M1 machine) is at home, but I'll check this later and come back here and close the issue if all looks well. Thanks for the quick fix!

**Comment by rob-p** [comment]
It works! Thanks @noamteyssier :).
